name: mlp_rusboost
family: tabular
class: hddpred.models.sklearn_models.SklearnModel
params:
  estimator: imblearn.ensemble.RUSBoostClassifier
  kwargs:
    n_estimators: 200
    learning_rate: 0.05
    sampling_strategy: auto
training:
  scale_inputs: true
