name: mlp_balanced_rf
family: tabular
class: hddpred.models.sklearn_models.SklearnModel
params:
  estimator: imblearn.ensemble.BalancedRandomForestClassifier
  kwargs:
    n_estimators: 300
    min_samples_leaf: 20
    max_features: sqrt
    sampling_strategy: auto
    replacement: true
    bootstrap: false
    n_jobs: 8
training:
  scale_inputs: true
