name: xgboost_balanced_bagging
family: tabular
class: hddpred.models.balanced_ensemble.BalancedEnsembleModel
params:
  base: configs/models/xgboost.yaml
  n_estimators: 10
  negative_ratio: 1
training: {}
